### ISSUE TITLE
unexpected status: 520  geoip.db

### ISSUE THREAD

**Issue by vahidsayad** [Chocolate4U/Iran-sing-box-rules#12]
Version 1.8.0 (169)

> (packet-tunnel) error: start service: Get "https://github.com/Chocolate4U/Iran-sing-box-rules/releases/latest/download/geoip.db": unexpected status: 520 

the URL is downloadable by browser but not working from sing-box app.

**Comment by Chocolate4U** [comment]
This is usually a network issue, try raw and jsDelivr links to see if they work for you:

`https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/release/geoip.db`

`https://cdn.jsdelivr.net/gh/chocolate4u/Iran-sing-box-rules@release/geoip.db`

Also I recommend using rule-set for sing-box 1.8.0+ because geoip.db and geosite.db are deprecated will probably get removed in later versions.
